### ISSUE TITLE
WiFi Spike

### ISSUE THREAD

**Issue by Paulpanther** [Paulpanther/RobotRace#1]
Arduino Code to send Debug Info (Tag + String) over WiFi to a PC (display in Console)

**Comment by Paulpanther** [comment]
#### TODO
- [ ] Control ESP
- [ ] Connect ESP with PC
- [ ] API for Arduino
- [ ] Console App for PC

**Comment by Paulpanther** [comment]
Used only arduino
