### ISSUE TITLE
Implement minimal Simulation

### ISSUE THREAD

**Issue by Paulpanther** [Paulpanther/RobotRace#3]
#### TODO
- [X] Display Circles
- [ ] Add LightSensor which returns light data (without noise for now) for given position
- [ ] Add Motor which changes the position/orientation (simplify to single motor)
- [ ] Add RobotWrapper around Robot Code to test
- [ ] If we want to embed C code, add WebSockets and C Wrapper

**Comment by Paulpanther** [comment]
Nope, we got a sim from class
